name: audiomob
description: "A Flutter plugin for integrating AudioMob audio ads into your Flutter applications."
version: 0.0.2
homepage: https://github.com/womanly-corp/audiomob-flutter-plugin

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wromance.audiomob
        pluginClass: AudiomobFlutterPlugin
