name: audiomob
description: "Flutter plugin for AudiMob audio ad monetization: https://audiomob.com/"
version: 0.0.2
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wromance.audiomob
        pluginClass: AudiomobFlutterPlugin
