name: audioadmob
description: "A plugin for integrating AudioMob audio ads into your Flutter applications."
version: 0.0.4
homepage: https://github.com/womanly-corp/audiomob-flutter-plugin

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  lints: ^5.1.1
  pigeon: ^25.3.0
  xsoulspace_lints: ^0.0.14

flutter:
  plugin:
    platforms:
      android:
        package: com.wromance.plugins.audioadmob
        pluginClass: AudiomobFlutterPlugin
        dartPluginClass: AndroidAudiomob
